version: "3"

services:
  test_runner:
    build: .
    image: pytest_runner
    container_name: pytest_runner_works
    environment:
      - ENV=dev  #prod or dev
    volumes:
      - .:/test_project/


# RUN   docker-compose up --build