version: "3"

services:
  test_runner:
    build: .
    image: pytest_runner
    container_name: pytest_runner_works
    environment:
      - ENV=dev
    volumes:
      - .:/test_project/

#artifacts: # Сущность, с помощью которой, мы сохраним результат тестирования.
#  when: always # Сохранять всегда
#  paths:
#    - ./allure-results # Здесь будет сохранен отчет
#  expire_in: 1 day # Да, он будет удален через день. Нет смысла хранить его в течение длительного срока.

# RUN   docker-compose up --build